### ISSUE TITLE
Moonlet Core - Zilliqa Blockchain Support - Task list

### ISSUE THREAD

**Issue by mickys** [cryptolandtech/moonlet-core#9]
- [x] #10 - Moonlet Core - Zilliqa Blockchain - Node
- [x] #11 - Moonlet Core - Zilliqa Blockchain - Transactions
- [x] #12 - Moonlet Core - Zilliqa Blockchain - Account
- [x] #13 - Moonlet Core - Zilliqa Blockchain - Account Utils

**Comment by mickys** [comment]
Implemented in https://github.com/cryptolandtech/moonlet-core/commit/213327852f6134d993a8640bd9ce3513536dd542
